@hostAddress=https://app01-gamestore-be-dev-austriaeast-01.azurewebsites.net

###
GET {{hostAddress}}/games 
###
GET {{hostAddress}}/games/1

###
POST {{hostAddress}}/games
Content-Type: application/json

{
    "name": "TEST GAME",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20"
}
###
POST {{hostAddress}}/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1991-02-01"
}
###
PUT {{hostAddress}}/games/5
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1992-07-15"
}
###
DELETE {{hostAddress}}/games/1

###
GET {{hostAddress}}/genres